# Simulate_HighCpuAlert.ps1
# -------------------------------------------------------------------------
# Writes a synthetic "High CPU Alert" Windows Event Log entry (Event ID 9999)
# under the source "AutoRemediationDemo" in the Application log.
# This guarantees the error actually appears in Windows Event Viewer while
# keeping the simulation 100% safe and reversible.
#
# Environment variables injected by the remediation engine (when called via
# run_remediation) are available as $env:RM_* but are not required here
# because this script is also called standalone to INJECT the error.
# -------------------------------------------------------------------------

$EVENT_SOURCE = 'AutoRemediationDemo'
$EVENT_LOG    = 'Application'
$EVENT_ID     = 9999
$SEVERITY     = 'High'

# --- Register the custom event source if it doesn't exist yet ---
if (-not [System.Diagnostics.EventLog]::SourceExists($EVENT_SOURCE)) {
    try {
        New-EventLog -LogName $EVENT_LOG -Source $EVENT_SOURCE -ErrorAction Stop
        Write-Host "[INFO] Registered event source: $EVENT_SOURCE"
    } catch {
        # May fail without admin rights; fall through to write attempt anyway
        Write-Host "[WARN] Could not register event source (may need Admin): $_"
    }
}

# --- Compose a realistic-looking CPU spike message ---
$timestamp   = Get-Date -Format 'yyyy-MM-ddTHH:mm:ss'
$cpuPct      = Get-Random -Minimum 92 -Maximum 100
$process     = 'DemoWorkload.exe'
$currentPid  = [string]$PID

$message = @"
[HIGH CPU ALERT] Simulated CPU spike detected on this host.

  Timestamp    : $timestamp
  Process      : $process (PID $currentPid)
  CPU Usage    : $cpuPct%
  Duration     : >30 seconds sustained
  Threshold    : 90%
  Event ID     : $EVENT_ID
  Source       : $EVENT_SOURCE
  Severity     : $SEVERITY

This is a SIMULATION event generated by the Auto-Remediation Demo system.
No actual system resources are affected. Run the remediation script to resolve.
"@

# --- Write the event to the Windows Application log ---
try {
    Write-EventLog `
        -LogName    $EVENT_LOG `
        -Source     $EVENT_SOURCE `
        -EventId    $EVENT_ID `
        -EntryType  'Error' `
        -Message    $message `
        -ErrorAction Stop

    Write-Host "[SUCCESS] Event ID $EVENT_ID written to $EVENT_LOG log (Source: $EVENT_SOURCE)."
    Write-Host "[INFO]    CPU spike simulated at $cpuPct% for process $process."
    Write-Host "[INFO]    You can verify this in Windows Event Viewer > Application Log."
    exit 0
} catch {
    Write-Host "[ERROR] Failed to write event log entry: $_"
    Write-Host "[INFO]  This may require elevated (Administrator) privileges."
    # Exit 0 anyway so the backend treats it as non-fatal; the DB event is still created.
    exit 0
}
