# Simulate_ServiceCrash.ps1
# -------------------------------------------------------------------------
# Writes a synthetic "Service Crash" Windows Event Log entry (Event ID 7034)
# under the source "AutoRemediationDemo" in the Application log.
#
# This guarantees the error actually appears in Windows Event Viewer while
# keeping the simulation 100% safe — NO actual service is stopped or modified.
#
# The real Windows Event ID 7034 is produced by the Service Control Manager
# (SCM) when a service crashes unexpectedly. We replicate the message format
# faithfully so the remediation engine's rule matching works correctly.
# -------------------------------------------------------------------------

$EVENT_SOURCE = 'AutoRemediationDemo'
$EVENT_LOG    = 'Application'
$EVENT_ID     = 7034
$SEVERITY     = 'High'
$SERVICE_NAME = 'PrintSpooler'
$DISPLAY_NAME = 'Print Spooler'

# --- Register the custom event source if it doesn't exist yet ---
if (-not [System.Diagnostics.EventLog]::SourceExists($EVENT_SOURCE)) {
    try {
        New-EventLog -LogName $EVENT_LOG -Source $EVENT_SOURCE -ErrorAction Stop
        Write-Host "[INFO] Registered event source: $EVENT_SOURCE"
    } catch {
        # May fail without admin rights; the DB event is still created by the backend
        Write-Host "[WARN] Could not register event source (may need Admin): $_"
    }
}

# --- Compose a realistic-looking service crash message (mirrors SCM format) ---
$timestamp  = Get-Date -Format 'yyyy-MM-ddTHH:mm:ss'
$crashCount = Get-Random -Minimum 1 -Maximum 5

$message = @"
[SERVICE CRASH ALERT] Windows Service terminated unexpectedly.

  Timestamp    : $timestamp
  Service Name : $SERVICE_NAME
  Display Name : $DISPLAY_NAME
  Crash Count  : $crashCount time(s) since last restart
  Event ID     : $EVENT_ID
  Source       : $EVENT_SOURCE
  Severity     : $SEVERITY

The $DISPLAY_NAME ($SERVICE_NAME) service terminated unexpectedly.
It has done this $crashCount time(s). The following corrective action will
be taken in 60000 milliseconds: Restart the service.

This is a SIMULATION event generated by the Auto-Remediation Demo system.
No actual system services are affected. Run the remediation script to resolve.
"@

# --- Write the event to the Windows Application log ---
try {
    Write-EventLog `
        -LogName    $EVENT_LOG `
        -Source     $EVENT_SOURCE `
        -EventId    $EVENT_ID `
        -EntryType  'Error' `
        -Message    $message `
        -ErrorAction Stop

    Write-Host "[SUCCESS] Event ID $EVENT_ID written to $EVENT_LOG log (Source: $EVENT_SOURCE)."
    Write-Host "[INFO]    Service crash simulated: $DISPLAY_NAME crashed $crashCount time(s)."
    Write-Host "[INFO]    You can verify this in Windows Event Viewer > Application Log."
    exit 0
} catch {
    Write-Host "[ERROR] Failed to write event log entry: $_"
    Write-Host "[INFO]  This may require elevated (Administrator) privileges."
    # Exit 0 anyway so the backend treats it as non-fatal; the DB event is still created.
    exit 0
}
